name: MAM_1
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.6.0=h6a678d5_0
  - blas=1.0=mkl
  - blosc=1.21.6=hf7d4471_0
  - brotli=1.0.9=h166bdaf_7
  - brotli-bin=1.0.9=h166bdaf_7
  - brotlicffi=1.0.9.2=py310h6a678d5_1
  - brunsli=0.1=h9c3ff4c_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cairo=1.16.0=he5ede1b_6
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py310h1fdaa30_1
  - cfitsio=3.470=hb418390_7
  - charls=2.2.0=h9c3ff4c_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cuda-version=12.9=3
  - dav1d=1.2.1=h5eee18b_0
  - expat=2.7.1=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.17.0=py310h06a4308_0
  - fontconfig=2.14.1=h55d465d_3
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - giflib=5.2.2=h5eee18b_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py310h5eee18b_0
  - gnutls=3.6.15=he1e5248_0
  - graphite2=1.3.14=h295c915_1
  - harfbuzz=10.2.0=hdfddeaa_1
  - icu=73.1=h6a678d5_0
  - idna=3.7=py310h06a4308_0
  - imagecodecs=2024.9.22=py310h787791d_2
  - imageio=2.37.0=pyhfb79c49_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.6=py310h06a4308_0
  - jpeg=9e=h5eee18b_3
  - jxrlib=1.2=hb25bd0a_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.19.3=h08a2579_0
  - lame=3.100=h7b6447c_0
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lazy_loader=0.4=pyhd8ed1ab_2
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libaec=1.1.3=h6a678d5_0
  - libavif=1.1.1=h5eee18b_0
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcblas=3.9.0=7_ha36c22a_netlib
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.14.1.1=4
  - libcurand=10.3.10.19=0
  - libcurl=7.79.1=h494985f_1
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.1.0=h767d61c_4
  - libgcc-ng=15.1.0=h69a702a_4
  - libgfortran=3.0.0=1
  - libgfortran-ng=13.2.0=h69a702a_0
  - libgfortran5=13.2.0=ha4646dd_0
  - libglib=2.84.2=h37c7471_0
  - libgomp=15.1.0=h767d61c_4
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - liblapack=3.9.0=7_ha36c22a_netlib
  - libnghttp2=1.43.0=ha19adfc_1
  - libnpp=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libpng=1.6.39=h5eee18b_0
  - libssh2=1.10.0=ha35d2d1_2
  - libstdcxx=15.1.0=h8f9b012_4
  - libstdcxx-ng=15.1.0=h4852527_4
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.7.0=hde9077f_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.8=hfdd30dd_0
  - libzopfli=1.0.3=h9c3ff4c_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py310h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_2
  - mkl_fft=1.3.11=py310h5eee18b_0
  - mkl_random=1.2.8=py310h1128e8f_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py310h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.4=pyhd8ed1ab_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=h0d4d230_1
  - openssl=3.5.1=h7b32b05_0
  - packaging=25.0=pyh29332c3_1
  - pcre2=10.42=hebb0a14_1
  - pillow=11.3.0=py310hb1c3d2d_0
  - pip=25.1=pyhc872135_2
  - pixman=0.40.0=h7f8727e_1
  - pthread-stubs=0.3=h0ce48e5_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.18=h1a3bd86_0
  - python_abi=3.10=2_cp310
  - pytorch=2.0.1=py3.10_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8=h7e8668a_6
  - pytorch-mutex=1.0=cuda
  - pywavelets=1.8.0=py310hf462985_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.4=py310h06a4308_0
  - scikit-image=0.25.0=py310h5eaa309_0
  - scipy=1.13.1=py310h93e2701_0
  - setuptools=78.1.1=py310h06a4308_0
  - snappy=1.2.1=h6a678d5_0
  - sqlite=3.50.2=hb25bd0a_1
  - sympy=1.13.3=py310h06a4308_1
  - tbb=2021.8.0=hdb19cb5_0
  - tifffile=2024.12.12=pyhd8ed1ab_0
  - tk=8.6.14=h993c535_1
  - torchtriton=2.0.0=py310
  - torchvision=0.15.2=py310_cu118
  - typing_extensions=4.12.2=py310h06a4308_0
  - urllib3=2.5.0=py310h06a4308_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zfp=1.0.0=h6a678d5_0
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_1
  - zlib-ng=2.0.7=h5eee18b_0
  - zstd=1.5.6=hc292b87_0
  - pip:
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - asciitree==0.3.3
      - av==15.0.0
      - click==8.2.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - diffusers==0.34.0
      - dill==0.4.0
      - einops==0.8.1
      - fasteners==0.19
      - fonttools==4.59.0
      - fsspec==2025.7.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - gym==0.26.2
      - gym-notices==0.1.0
      - h5py==3.14.0
      - hf-xet==1.1.5
      - huggingface-hub==0.34.3
      - hydra-core==1.3.2
      - kiwisolver==1.4.8
      - llvmlite==0.44.0
      - matplotlib==3.10.5
      - numba==0.61.2
      - numcodecs==0.13.1
      - numpy==1.26.4
      - omegaconf==2.3.0
      - opencv-python==4.8.1.78
      - pandas==2.3.1
      - platformdirs==4.3.8
      - protobuf==6.31.1
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pygame==2.6.1
      - pymunk==7.1.0
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2025.7.34
      - safetensors==0.5.3
      - sentry-sdk==2.34.1
      - shapely==2.1.1
      - six==1.17.0
      - smmap==5.0.2
      - tqdm==4.67.1
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - wandb==0.21.0
      - zarr==2.18.3
prefix: /home/ybli/miniconda3/envs/zy_dp_py310